default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: deployment_development

test:
  <<: *default
  database: deployment_test

staging:
  <<: *default
  database: deployment_staging

production:
  <<: *default
  database: deployment_production
  username: root
  password: <%= ENV["DPLOYMENT_DATABASE_PASSWORD"] %>
